export { default as InputForm } from "./InputForm";
export { default as Header } from "./Header";
export { default as Button } from "./Button";
export { default as Label } from "./Label";
export { default as HeaderAndInput } from "./HeaderAndInput";
export { default as DeleteForm } from "./DeleteForm";
export { default as AddForm } from "./AddForm";
export { default as FooterPage } from "./FooterPage";
export { default as Nav } from "./Nav";
